services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false    

    Ibexa\ExampleInMemoryProductCatalog\PIM\InMemory\Data\DataProvider: ~

    Ibexa\ExampleInMemoryProductCatalog\PIM\InMemory\AssetService:
        tags:
            -   name: ibexa.product_catalog.asset_service
                engine: in_memory

    Ibexa\ExampleInMemoryProductCatalog\PIM\InMemory\AttributeGroupService:
        tags:
            -   name: ibexa.product_catalog.attribute_group_service
                engine: in_memory

    Ibexa\ExampleInMemoryProductCatalog\PIM\InMemory\AttributeDefinitionService:
        tags:
            -   name: ibexa.product_catalog.attribute_definition_service
                engine: in_memory

    Ibexa\ExampleInMemoryProductCatalog\PIM\InMemory\ProductTypeService:
        tags:
            -   name: ibexa.product_catalog.product_type_service
                engine: in_memory

    Ibexa\ExampleInMemoryProductCatalog\PIM\InMemory\ProductService:
        tags:
            -   name: ibexa.product_catalog.product_service
                engine: in_memory
